config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/add_ingredient", to: "ingredients#new"

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users do
    resources :profiles
  end

  resources :goals

  resources :daily_logs do
    resources :meals do
      resources :foods
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-36x36.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-48x48.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-72x72.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-96x96.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-144x144.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_navbar.html.erb
<br><br><br>
<div class='d-flex justify-content-around align-items-center navbar-phone'>
    <% if @current_daily_log.present? %>
      <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740221200/home_he5j7u.png"), daily_log_path(@current_daily_log), class: "img-fluid" %>
    <% else %>
      <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740221200/home_he5j7u.png"), new_daily_log_path, class: "img-fluid" %>
    <% end %>

    <% if current_user.present? && current_user.goal.present? %>
      <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740221200/graph_tvenik.png"), goal_path(current_user.goal), class: "img-fluid" %>
    <% else %>
      <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740221200/graph_tvenik.png"), new_goal_path, class: "img-fluid" %>
    <% end %>

    <% if user_signed_in? %>
      <% if defined?(edit_user_profile_path) && defined?(new_user_profile_path) %>
        <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740497500/profile-user_m09yqp.png"), edit_user_profile_path(current_user.id, 1), class: "img-fluid" %>
      <% else %>
        <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740497500/profile-user_m09yqp.png"), new_user_profile_path(current_user.id), class: "img-fluid" %>
      <% end %>
    <% else %>
      <%= link_to image_tag("https://res.cloudinary.com/dz68ybmap/image/upload/v1740497500/profile-user_m09yqp.png"), new_user_session_path, class: "img-fluid" %>
    <% end %>
</div>