config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/add_ingredient", to: "ingredients#new"

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users do
    resources :profiles
  end

  resources :goals

  resources :daily_logs do
    resources :meals do
      resources :foods
    end
  end
end

app/models/daily_log.rb
class DailyLog < ApplicationRecord
  belongs_to :user
  has_many :meals, dependent: :destroy

  def total_calories
    meals.sum(&:total_calories)
  end

  def total_protein
    meals.sum(&:total_protein)
  end

  def total_carbs
    meals.sum(&:total_carbs)
  end

  def total_fat
    meals.sum(&:total_fat)
  end

  def update_remaining_nutrients
    return unless user.goal

    update(
      remaining_calories: user.goal.daily_calorie_target - total_calories,
      remaining_proteins: user.goal.protein_target - total_protein,
      remaining_carbs: user.goal.carbs_target - total_carbs,
      remaining_fats: user.goal.fat_target - total_fat
    )
  end
end

app/controllers/daily_logs_controller.rb
class DailyLogsController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  before_action :set_daily_log, only: %i[show update destroy]

  def show
    @daily_log = DailyLog.find(params[:id])
    @user = current_user
    @meal = Meal.new
  end

  def create
    @daily_log = current_user.daily_logs.new(daily_log_params)
    if @daily_log.save
      render json: @daily_log, status: :created
    else
      render json: @daily_log.errors, status: :unprocessable_entity
    end
  end

  def update
    if @daily_log.update(daily_log_params)
      render json: @daily_log
    else
      render json: @daily_log.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @daily_log.destroy
    head :no_content
  end

  private

  def set_user
    @user = current_user
  end

  def set_daily_log
    @daily_log = current_user.daily_logs.find(params[:id])
  end

  def daily_log_params
    params.require(:daily_log).permit(:user_id, :log_date, :remaining_calories, :remaining_proteins, :remaining_carbs, :remaining_fats, :remaining_water)
  end
end

app/views/daily_logs/edit.html.erb
<h1>DailyLogs#edit</h1>
<p>Find me in app/views/daily_logs/edit.html.erb</p>

app/views/daily_logs/index.html.erb
<h1>DailyLogs#index</h1>
<p>Find me in app/views/daily_logs/index.html.erb</p>

app/views/daily_logs/show.html.erb
<body>
  <section id="remaining_calories"><% @daily_log.remaining_calories.round %></section>
  <section id="daily_calorie_target"><% @user.goal.daily_calorie_target %></section>
    <div class="container">
        <header>
            <h1><img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1740221192/dish_f16ncn.png" alt="Logo"> TrackMyPlate</h1>
            <p>Today</p>
        </header>
        <section class="calories">
              <div>
                <% calories_eat = 0 %>
                <% @daily_log.meals.each do |meal| %>
                  <%# <% a = calories_eat %>
                  <% calories_eat = meal.total_calories.round %>
                <% end %>
                <h2><%= @daily_log.remaining_calories.round - calories_eat %></h2>
                <% calories_eat = 0 %>
                <p>Calories left</p>
              </div>
              <div class="progress-container">
                <svg width="120" height="120" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r="40" stroke="#ddd" stroke-width="10" fill="none" />
                    <circle id="progress" cx="50" cy="50" r="40" stroke="#555" stroke-width="10" fill="none"
                            stroke-linecap="round" stroke-dasharray="251.2" stroke-dashoffset="251.2" />
                </svg>
              <div class="icon"><img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604725/calories_xmrfkk.png"></div>
              </div>
        </section>
        <section class="macros">
                <% protein_eat = 0 %>
                <% @daily_log.meals.each do |meal| %>
                  <% protein_eat = meal.total_protein.round %>
                <% end %>

                <% carbs_eat = 0 %>
                <% @daily_log.meals.each do |meal| %>
                  <% carbs_eat = meal.total_carbs.round %>
                <% end %>

                <% fat_eat = 0 %>
                <% @daily_log.meals.each do |meal| %>
                  <% fat_eat = meal.total_fat.round %>
                <% end %>

            <div class="macro">
                <p><strong class="gbold"><%= @daily_log.remaining_proteins - protein_eat %>g </strong><br> Protein left</p>
                <img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604767/meat_zs6xru.png" alt="Protein">
            </div>
            <div class="macro">
                <p><strong class="gbold"><%= @daily_log.remaining_carbs - carbs_eat %>g </strong><br> Carbs left</p>
                <img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604767/starch_cstc5l.png" alt="Carbs">
            </div>
            <div class="macro">
                <p><strong class="gbold"><%= @daily_log.remaining_fats - fat_eat %>g </strong><br> Fats left</p>
                <img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604767/fat_svz8zd.png" alt="Fats">
            </div>
            <% protein_eat = 0 %>
            <% carbs_eat = 0 %>
            <% fat_eat = 0 %>
        </section>
        <section class="meals">
        <p>Recently uploaded</p>
            <% @daily_log.meals.each do |meal| %>
              <div class="meal">
              <% image = "" %>
              <% if meal.foods.any? && meal.foods.last.food_name == "Burger"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274747/burger_xwukmm.jpg"
              elsif meal.foods.any? && meal.foods.last.food_name == "Pancakes"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274694/panacakes_whyntg.jpg"
              elsif meal.foods.any? && meal.foods.last.food_name == "Salad"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274694/salad_rfh2oz.jpg"
              elsif meal.foods.any? && meal.foods.last.food_name == "Pasta"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274695/pasta_dljae6.jpg"
              elsif meal.foods.any? && meal.foods.last.food_name == "Pizza"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274696/pizza_ufpsjn.webp"
              elsif meal.foods.any? && meal.foods.last.food_name == "Fish"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274848/fish_jvzbzq.webp"
              elsif meal.foods.any? && meal.foods.last.food_name== "Steak"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274848/steak_bzlfoi.jpg"
              elsif meal.foods.any? && meal.foods.last.food_name == "Chicken"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274848/chicken_qs5cea.jpg"
              elsif meal.foods.any? && meal.foods.last.food_name == "Kebab"
                image = "https://res.cloudinary.com/dz68ybmap/image/upload/v1741274694/lamb-shish-kebab-20_lhosbq.jpg"
              end %>
                <img class="meal-image" src= "<%= image %>" alt="Repas">
                <div class="meal-info">
                    <div class="meal-header">
                        <h3><%= link_to "#{meal.meal_type}", daily_log_meal_path(@daily_log.id, meal.id) %></h3>
                        <span class="meal-time"><%= meal.eaten_at.strftime("%H:%M") %></span>
                    </div>
                    <p class="meal-calories">
                        <img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604725/calories_xmrfkk.png" class="icons"> <%= meal.total_calories.round %> kcal
                    </p>
                    <div class="meal-macros">
                        <p><img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604767/meat_zs6xru.png" alt="Protein"> <%= meal.total_protein.round %>g</p>
                        <p><img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604767/starch_cstc5l.png" alt="Carbs"> <%= meal.total_carbs.round %>g</p>
                        <p><img src="https://res.cloudinary.com/dz68ybmap/image/upload/v1739604767/fat_svz8zd.png" alt="Fats"> <%= meal.total_fat.round %>g</p>
                    </div>
                </div>
              </div>
            <% end %>
        </section>
        <div class="idea-button">
        <%= link_to "#", class: "idea-icon", data: { bs_toggle: "modal", bs_target: "#ideaPopup" } do %>
          <i class="fas fa-lightbulb"></i>
        <% end %>
        </div>
        <button class="add-meal"><%= link_to "+", new_daily_log_meal_path(@daily_log.id, @meal) %></button>
    </div>
</body>

<div class="modal fade" id="ideaPopup" tabindex="-1" aria-labelledby="ideaPopupLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ideaPopupLabel">Suggestion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% client = OpenAI::Client.new
        chatgpt_response = client.chat(parameters: {
          model: "gpt-3.5-turbo",
          messages: [{ role: "user", content: "Tu es un expert en nutrition. Ta tâche consiste à proposer des repas en fonction des calories, protéines, glucides, lipides restants et en fonction de son objectif. Voici les données: calories = #{@daily_log.remaining_calories}, protéines = #{@daily_log.remaining_proteins}, glucides = #{@daily_log.remaining_carbs}, lipides = #{@daily_log.remaining_fats}, objectif = #{@user.goal.goal_type}. Renvoie uniquement les repas avec des gros espaces pour plus de visibilité avec les données en premier et les repas avec les données du repas."}]
        })
        @content = chatgpt_response["choices"][0]["message"]["content"] %>

      <%= @content %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>