config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/add_ingredient", to: "ingredients#new"

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users do
    resources :profiles
  end

  resources :goals

  resources :daily_logs do
    resources :meals do
      resources :foods
    end
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :meal
  has_one :nutrition, dependent: :destroy
  has_one_attached :photo

  after_save :update_daily_log_remaining_nutrients

  after_destroy :update_daily_log_remaining_nutrients

  # enum serving_unit: {
  #   grams: 'grams'
  #   liters: 'liters'
  #   cups: 'cups'
  #   tablespoons: 'tablespoons'
  #   teaspoons: 'teaspoons'
  # }

  private

  def update_daily_log_remaining_nutrients
    meal.daily_log.update_remaining_nutrients
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_meal, only: [:new, :create]

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @daily_log = current_user.daily_logs.find(params[:daily_log_id])
    @meal = @daily_log.meals.find(params[:meal_id])
    @food = Food.new
  end

  def create
    Rails.logger.debug("Meal ID from Params: #{params[:meal_id]}")
    @food = @meal.foods.build(food_params)
    if @food.save
      redirect_to daily_log_meal_path(@daily_log, @meal), notice: "Aliment ajouté avec succès."
      client = OpenAI::Client.new
      chatgpt_response = client.chat(parameters: {
        model: "gpt-3.5-turbo",
        messages: [{ role: "user", content: "Tu es un expert en nutrition. Ta tâche est de calculer les valeurs nutritionnelles d'un repas. Voici le repas : #{@food.food_name}, #{@food.serving_size}#{@food.serving_unit}. Renvoie uniquement un Hash Ruby avec les valeurs arrondies et dans cet ordre exact : { calories: ?, protein: ?, carbs: ?, fat: ? }. Assure-toi que les nombres sont toujours entiers et ne contiennent jamais de décimales."}]
      })
      @content = chatgpt_response["choices"][0]["message"]["content"]

      @data = eval(@content)

      @nutrition = Nutrition.create(food: @food, calories: @data[:calories], protein: @data[:protein], carbs: @data[:carbs], fat: @data[:fat])

    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_meal
    @daily_log = current_user.daily_logs.find(params[:daily_log_id])
    @meal = @daily_log.meals.find(params[:meal_id])
  end

  def food_params
    params.require(:food).permit(:food_name, :serving_size, :serving_unit, :food_id)
  end
end

app/views/foods/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Add a food</title>

</head>
<body>

  <div class="container">

    <form>
        <h1 class="food-title">Add a food</h1>

        <div class="form-group">
            <label for="food-name">Food name</label>
            <input type="text" id="food-name" name="food-name">
        </div>

        <div class="form-group">
            <label for="serving-size">Serving size</label>
            <input type="text" id="serving-size" name="serving-size">
        </div>

        <div class="form-group">
            <label for="serving-unit">Serving unit</label>
            <input type="text" id="serving-unit" name="serving-unit">
        </div>

        <button type="submit">Create Food</button>
    </form>

</div>
  <button class="big-black-btn">Create Food</button>
</body>
</html>

app/views/foods/new.html.erb
<h1>Add a food</h1>

<%= simple_form_for [@daily_log, @meal, @food], url: daily_log_meal_foods_path(@daily_log, @meal) do |f| %>
  <%= f.input :food_name %>
  <%= f.input :serving_size %>

  <div class="form-group serving-unit-group">
    <label class="form-label">Serving Unit</label>
    <div class="serving-unit-options">
      <% serving_units = ['g', 'kg', 'L', 'mL' , 'cups', 'pieces', 'slices', 'bars', 'squares'] %>
      <% serving_units.each do |unit| %>
        <div class="serving-unit-option">
          <%= f.radio_button :serving_unit, unit, class: 'form-check-input' %>
          <%= f.label "serving_unit_#{unit}", unit.capitalize, class: 'form-check-label' %>
        </div>
      <% end %>
    </div>
  </div>

  <%= f.button :submit, class: 'add-ingredient' %>
<% end %>

app/views/foods/show.html.erb
<h1><%= @food.food_name %></h1>
<p>Portion : <%= @food.serving_size %> <%= @food.serving_unit %></p>